"""add topic to outbox message

Revision ID: da5cb8b1aa6c
Revises: e46273e93bf2
Create Date: 2026-09-06 14:07:08.894420

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da5cb8b1aa6c"
down_revision: str | Sequence[str] | None = "e46273e93bf2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox_message", sa.Column("topic", sa.String(length=100), nullable=True))
    op.execute("UPDATE outbox_message SET topic = 'auth-events' WHERE topic IS NULL")
    op.alter_column("outbox_message", "topic", nullable=False)
    op.execute("ALTER TYPE outmessagestatus RENAME TO outboxmessagestatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE outboxmessagestatus RENAME TO outmessagestatus")
    op.drop_column("outbox_message", "topic")
    # ### end Alembic commands ###
