"""add saga instance and invite org fields

Revision ID: e46273e93bf2
Revises: 3eca849eed00
Create Date: 2026-09-06 13:06:15.071445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46273e93bf2'
down_revision: Union[str, Sequence[str], None] = '3eca849eed00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saga_instance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('saga_type', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('struct_adm_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('current_step', sa.Enum('STARTED', 'ORG_ASSIGN_SENT', 'TASK_CREATE_SENT', 'COMPLETED', 'COMPENSATING_ORG', 'COMPENSATING_INVITE', 'COMPENSATED', name='sagastep'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'COMPENSATING', 'COMPENSATED', 'FAILED', name='sagastatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saga_instance_employee_id'), 'saga_instance', ['employee_id'], unique=False)
    op.add_column('invite', sa.Column('struct_adm_id', sa.UUID(), nullable=True))
    op.add_column('invite', sa.Column('position_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'position_id')
    op.drop_column('invite', 'struct_adm_id')
    op.drop_index(op.f('ix_saga_instance_employee_id'), table_name='saga_instance')
    op.drop_table('saga_instance')
    # ### end Alembic commands ###
