version: "3.8"

services:
  db:
    image: postgres:18
    container_name: first-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: first
    ports:
      - "5432:5432"

volumes:
  postgres_data:
