# org-service/app/repositories/__init__.py
from .company_repository import CompanyRepository
from .inbox_message_repository import InboxMessageRepository
from .outbox_message_repository import OutboxMessageRepository
from .position_repository import PositionRepository
from .struct_adm_position_repository import StructAdmPositionRepository
from .struct_adm_repository import StructAdmRepository
from .user_position_repository import UserPositionRepository
from .user_repository import UserRepository
