version: "3.8"

services:
  db:
    image: postgres:18
    container_name: second-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: second
    ports:
      - "5433:5432"

volumes:
  postgres_data:
