"""add processing status to outbox

Revision ID: 25ff5f45763d
Revises: 600ff72fe7cc
Create Date: 2026-09-13 00:38:31.317247

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25ff5f45763d"
down_revision: str | Sequence[str] | None = "600ff72fe7cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE outboxmessagestatus ADD VALUE IF NOT EXISTS 'PROCESSING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
