"""add topic to outbox message

Revision ID: 3f32a17e7426
Revises: b1cec24233fc
Create Date: 2026-09-06 14:09:42.076088

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f32a17e7426"
down_revision: str | Sequence[str] | None = "b1cec24233fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox_message", sa.Column("topic", sa.String(length=100), nullable=True))
    op.execute("UPDATE outbox_message SET topic = 'auth-events' WHERE topic IS NULL")
    op.alter_column("outbox_message", "topic", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_message", "topic")
    # ### end Alembic commands ###
