"""add outbox retry fields

Revision ID: 571b4df3452c
Revises: 3f32a17e7426
Create Date: 2026-09-07 09:26:45.708526

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "571b4df3452c"
down_revision: str | Sequence[str] | None = "3f32a17e7426"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE outboxmessagestatus ADD VALUE IF NOT EXISTS 'DEAD'")
    op.add_column("outbox_message", sa.Column("next_retry_at", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_message", "next_retry_at")
    # ### end Alembic commands ###
