"""add processing status to outbox

Revision ID: 58784e2af129
Revises: 7b510ff9ee15
Create Date: 2026-09-13 00:37:59.112208

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58784e2af129"
down_revision: str | Sequence[str] | None = "7b510ff9ee15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE outboxmessagestatus ADD VALUE IF NOT EXISTS 'PROCESSING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
