"""add timestamps to user_position

Revision ID: 589b568163cb
Revises: 0947bb6b5603
Create Date: 2026-09-03 22:06:16.403126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589b568163cb'
down_revision: Union[str, Sequence[str], None] = '0947bb6b5603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_struct_adm_path_gist'), table_name='struct_adm', postgresql_using='gist')
    op.add_column('user_position', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_position', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_user_position_user_id_position_id', 'user_position', ['user_id', 'position_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_position_user_id_position_id', 'user_position', type_='unique')
    op.drop_column('user_position', 'deleted_at')
    op.drop_column('user_position', 'created_at')
    op.create_index(op.f('ix_struct_adm_path_gist'), 'struct_adm', ['path'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
