"""restore gist index on struct_adm path

Revision ID: ca05a8c0bc7c
Revises: 589b568163cb
Create Date: 2026-09-03 22:09:00.978485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca05a8c0bc7c'
down_revision: Union[str, Sequence[str], None] = '589b568163cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_struct_adm_path_gist', 'struct_adm', ['path'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_struct_adm_path_gist', table_name='struct_adm', postgresql_using='gist')
    # ### end Alembic commands ###
